version: '3.8'

services:
  # Service 'mongo' DIHAPUS karena kita menggunakan yang sudah ada
  backend:
    build: ./backend
    container_name: americano-backend
    restart: always
    ports:
      - "8180:8080"
    environment:
      # Ganti 'mongo' dengan nama container existing Anda (misal: mongolatest)
      # Pastikan port tetap 27017 (port internal docker), bukan port host (27019)
      - MONGODB_URI=mongodb://americano-mongo:27017/coffeeshop
      - PORT=8080
      - ALLOWED_ORIGINS=http://localhost:8085,http://localhost:8180,https://nyafe.widifirmaan.web.id,http://localhost:3000
    volumes:
      - uploads_data:/app/uploads
    # depends_on dihapus karena service mongo tidak ada di file ini
    networks:
      - coffeeshop_network

  frontend:
    build: ./frontend
    container_name: americano-frontend
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - backend
    networks:
      - coffeeshop_network

volumes:
  uploads_data:


networks:
  coffeeshop_network:
    external: true # PENTING: Menandakan network ini sudah dibuat di luar compose
