version: '3.8'

services:
  # mongo service uses existing 'americano-mongo' container on 'root_default' network

  backend:
    build: ./backend
    container_name: americano-backend
    restart: always
    ports:
      - "8180:8080"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@cluster0.yrb9vc6.mongodb.net/coffeeshop?appName=Cluster0
      - PORT=8080
      - ALLOWED_ORIGINS=http://localhost:8085,http://localhost:8180,https://nyafe.widifirmaan.web.id

  frontend:
    build: ./frontend
    container_name: americano-frontend
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - backend

networks:
  default:
    external: true
    name: root_default
